# Generated by Django 4.2.5 on 2023-09-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('nivel', models.PositiveIntegerField()),
            ],
        ),
    ]
