# Generated by Django 4.2.5 on 2023-09-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
