# Generated by Django 4.2.5 on 2023-09-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
