# Generated by Django 4.2.5 on 2023-09-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_character_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='nivel',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
