# Generated by Django 4.2.5 on 2023-09-15 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_character_nivel'),
        ('clan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clan',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clan',
            name='nivel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ClanMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan', to='character.character')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clan.clan')),
            ],
        ),
    ]
