# Generated by Django 4.2.5 on 2023-09-15 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_character_nivel'),
        ('clan', '0002_clan_description_clan_name_clan_nivel_clanmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='leader',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clan_leader', to='character.character'),
            preserve_default=False,
        ),
    ]
