# Generated by Django 4.2.5 on 2023-09-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_character_nivel'),
        ('clan', '0003_clan_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanmember',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_member', to='character.character'),
        ),
    ]
